[options]
Architecture = x86_64
CacheDir = /home/gullin/PrismLauncher-Cracked-src/.msys2-win64/var/cache/pacman/pkg
SigLevel = Never
LocalFileSigLevel = Never
DisableDownloadTimeout

[mingw64]
Server = https://repo.msys2.org/mingw/mingw64

[msys]
Server = https://repo.msys2.org/msys/x86_64
